#generated by Django 3.8.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ('network', '0001_initial')       
    ]

    operations = [
        migrations.AddField(
            model_name= 'user',
            name= 'following',
            field= models.ManyToManyField(blank=True, null=True, related_name='_user_following_+', to=settings.AUTH_USER_MODEL)
        ),
        migrations.CreateModel(
            name = 'post',
            fields = [
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=280)),
                ('likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]

