# Generated by Django

from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20200908_232')
    ]

    operations = [
        migrations.AlterField(
            model_name= 'user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_user_following_+', to=settings.AUTH_USER_MODEL),
        ),
    ]

